title: Mar de Gatos
email: contacto@mardegatos.org
description: >-
  Mar de Gatos es un grupo de personas que ofrecen su tiempo y esfuerzo para
  rescatar gatitos en situación de calle, abandono y maltrato en la ciudad de Puerto Madryn.
baseurl: ""
url: "https://www.mardegatos.org"

# Build settings
markdown: kramdown
theme: minima
include:
  - .well-known
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
